---
blueprint:
  key: rh-ai-fsxn
  title: Red Hat OpenShit AI
  cloud: AWS
  description: A Red Hat OpenShift AI instance running in AWS with Trident configured with FSxN.

stack:
  platform: rosa
  components:
    - trident
    - fsxn
    - rhoai

workflow:
  orchestrators:
    - opentofu
    - rosactl
    - kubectl

    
